import { useCallback, useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { api, ApiError } from "../api/client";
import { DisclaimerFooter } from "../components/DisclaimerFooter";
import { AnalysisPanel } from "../components/AnalysisPanel";
import { Drawer } from "../components/Drawer";
import { FilingItemCard } from "../components/FilingItemCard";
import { JobProgress } from "../components/JobProgress";
import { MetricTable } from "../components/MetricTable";
import { SectionHeader } from "../components/SectionHeader";
import { useBootstrap } from "../context/BootstrapContext";
import { useResource } from "../hooks/useResource";
import type { Brief, FilingType, Job } from "../types";

export function BriefPage() {
  const location = useLocation(); const navigate = useNavigate(); const { bootstrap } = useBootstrap();
  const params = new URLSearchParams(location.search); const demo = params.get("demo") === "1"; const panel = params.get("panel");
  const [job, setJob] = useState<Job | null>(null); const [actionError, setActionError] = useState("");
  const load = useCallback((signal: AbortSignal) => api<Brief>(`/api/brief?demo=${demo}`, { signal }), [demo]);
  const resource = useResource(load, [demo]);
  useEffect(() => {
    if (!job || !["queued", "running"].includes(job.state)) return;
    const timer = window.setInterval(() => api<Job>(`/api/jobs/${job.id}`).then(next => { setJob(next); if (!["queued", "running"].includes(next.state)) resource.refresh(); }).catch(reason => { setActionError(reason instanceof ApiError ? reason.message : "Job status was lost after a restart."); setJob(null); }), 700);
    return () => window.clearInterval(timer);
  }, [job, resource.refresh]);
  async function start(kind: "sync" | "analyze", formType: FilingType = "latest") { setActionError(""); const payload = formType === "latest" ? {} : { form_type: formType }; try { setJob(await api<Job>(`/api/jobs/${kind === "sync" ? "sync" : "analyze"}`, { method: "POST", body: JSON.stringify(payload) })); } catch (reason) { setActionError(reason instanceof ApiError ? reason.message : "Operation could not start."); } }
  function closePanel() { params.delete("panel"); navigate({ pathname: location.pathname, search: params.toString() }, { replace: true }); }
  if (!resource.data && resource.loading) return <main className="page"><p className="loading">Loading the brief…</p></main>;
  if (!resource.data) return <main className="page"><div className="notice">{resource.error?.message ?? "The brief is unavailable."}</div></main>;
  const brief = resource.data;
  const trackedTickers = brief.tracked_tickers;
  const answerTone = brief.answer_posture === "risk_review" ? "attention" : brief.answer_posture === "monitor" || brief.answer_posture === "positive_support" ? "calm" : "";
  return <main className="page">
    {brief.sample_data && <div className="notice neutral">Sample data · generated by the bundled recorded pipeline</div>}
    {resource.error && <div className="notice">Could not refresh. Showing the last successful brief.</div>}
    <header className="brief-header"><div><p className="page-eyebrow"><span className="status-dot" aria-hidden="true" />Your filing watch</p><h1 className="page-title">Filing brief</h1><p className="page-subtitle">A concise, evidence-backed read on what changed across the companies you follow.</p></div><div className="actions">{!demo && <><button className="button" onClick={() => start("sync")}><span aria-hidden="true">↻</span> Sync filings</button><button className="button primary" onClick={() => navigate("?panel=analysis")}>Analyze a filing <span aria-hidden="true">→</span></button></>} {demo && <button className="button" onClick={() => navigate("/brief")}>Exit sample</button>}</div></header>
    <section className={`brief-hero ${answerTone}`}>
      <div className="hero-copy"><span className="hero-label">Executive read</span><p className="answer-hero">{brief.answer}</p><p className="hero-note">AI-selected significance · exact evidence verified before publication</p></div>
      <div className="brief-stats">
        <div><span>Period</span><strong>{brief.period.covered}</strong></div>
        <div><span>Indexed</span><strong>{brief.period.filings_in_window}</strong><small>filings in view</small></div>
        <div><span>Analyzed</span><strong>{brief.period.analyzed_filings}</strong><small>verification gated</small></div>
      </div>
    </section>
    <div className="ticker-strip"><span>Tracking</span>{trackedTickers.length ? trackedTickers.map(ticker => <span className="ticker-chip" key={ticker}>{ticker}</span>) : <span className="empty-inline">No tickers yet</span>}</div>
    {actionError && <div className="notice">{actionError}</div>}<JobProgress job={job} />
    {brief.withheld_filings.length > 0 && <section className="surface section"><SectionHeader index="00" title="Withheld analyses" />{brief.withheld_filings.map(filing => <FilingItemCard key={filing.accession} filing={filing} withholdFindings />)}<p className="notice">Language-model content stays hidden until deterministic verification passes.</p></section>}
    <section className="surface section"><SectionHeader index="01" title="What changed" /><p className="metric-caption">The model selects significance; RipplX independently checks that every displayed quotation matches the SEC filing exactly.</p>{brief.filings.length ? brief.filings.map(filing => <FilingItemCard key={filing.accession} filing={filing} />) : <div className="empty-state"><span aria-hidden="true">✓</span><div><strong>No evidence-backed changes selected</strong><p>The latest analyzed filing did not produce a finding that cleared the publication gate.</p></div></div>}</section>
    <section className="surface section"><SectionHeader index="02" title="Verified numbers" /><p className="metric-caption">Versioned formulas compute these values directly from SEC XBRL facts—never from the language model. ✓ indicates a computed result; — means unavailable or not applicable.</p>{brief.verified_numbers.map(issuer => <article className="issuer-block" key={issuer.ticker}><h3 className="issuer-title"><span className="ticker-avatar small">{issuer.ticker.slice(0, 2)}</span>{issuer.ticker}</h3>{issuer.empty ? <p className="empty-line">{issuer.ticker}: {issuer.empty}</p> : <MetricTable rows={issuer.rows} />}</article>)}</section>
    <section className="surface section"><SectionHeader index="03" title="Open questions" />{brief.open_questions.length ? <ul className="question-list">{brief.open_questions.map((question, index) => <li className="muted" key={index}>{question}</li>)}</ul> : <div className="empty-state compact"><span aria-hidden="true">✓</span><div><strong>No open questions</strong><p>Nothing in this brief needs a follow-up review.</p></div></div>}</section>
    {brief.boring_filings && <div className="faint section">{brief.boring_filings}</div>}
    <DisclaimerFooter text={brief.disclaimer} />
    {panel === "analysis" && <Drawer title="Run filing analysis" onClose={closePanel}><AnalysisPanel configured={bootstrap.analysis_configured} onAnalyze={formType => { closePanel(); start("analyze", formType); }} onConfigure={() => navigate("/settings")} onDemo={() => navigate("/brief?demo=1")} /></Drawer>}
  </main>;
}
