import { useCallback, useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { api, ApiError } from "../api/client";
import { DisclaimerFooter } from "../components/DisclaimerFooter";
import { Drawer } from "../components/Drawer";
import { FilingItemCard } from "../components/FilingItemCard";
import { JobProgress } from "../components/JobProgress";
import { MetricTable } from "../components/MetricTable";
import { SectionHeader } from "../components/SectionHeader";
import { useBootstrap } from "../context/BootstrapContext";
import { useResource } from "../hooks/useResource";
import type { Brief, Job } from "../types";

export function BriefPage() {
  const location = useLocation(); const navigate = useNavigate(); const { bootstrap } = useBootstrap();
  const params = new URLSearchParams(location.search); const demo = params.get("demo") === "1"; const panel = params.get("panel");
  const [job, setJob] = useState<Job | null>(null); const [actionError, setActionError] = useState("");
  const load = useCallback((signal: AbortSignal) => api<Brief>(`/api/brief?demo=${demo}`, { signal }), [demo]);
  const resource = useResource(load, [demo]);
  useEffect(() => {
    if (!job || !["queued", "running"].includes(job.state)) return;
    const timer = window.setInterval(() => api<Job>(`/api/jobs/${job.id}`).then(next => { setJob(next); if (!["queued", "running"].includes(next.state)) resource.refresh(); }), 700);
    return () => window.clearInterval(timer);
  }, [job, resource.refresh]);
  async function start(kind: "sync" | "analyze") { setActionError(""); try { setJob(await api<Job>(`/api/jobs/${kind === "sync" ? "sync" : "analyze"}`, { method: "POST", body: "{}" })); } catch (reason) { setActionError(reason instanceof ApiError ? reason.message : "Operation could not start."); } }
  function closePanel() { params.delete("panel"); navigate({ pathname: location.pathname, search: params.toString() }, { replace: true }); }
  if (!resource.data && resource.loading) return <main className="page"><p className="loading">Loading the brief…</p></main>;
  if (!resource.data) return <main className="page"><div className="notice">{resource.error?.message ?? "The brief is unavailable."}</div></main>;
  const brief = resource.data;
  const answerTone = brief.answer_posture === "risk_review" ? "attention" : brief.answer_posture === "monitor" || brief.answer_posture === "positive_support" ? "calm" : "";
  return <main className="page">
    {brief.sample_data && <div className="notice neutral">Sample data · generated by the bundled recorded pipeline</div>}
    {resource.error && <div className="notice">Could not refresh. Showing the last successful brief.</div>}
    <p className={`answer-hero ${answerTone}`}>{brief.answer}</p>
    <header><div className="page-header"><h1 className="page-title">RipplX digest</h1><div className="actions">{!demo && <><button className="button" onClick={() => start("sync")}>Sync filings</button><button className="button secondary" onClick={() => navigate("?panel=analysis")}>Run analysis</button></>} {demo && <button className="button" onClick={() => navigate("/brief")}>Exit sample</button>}</div></div><div className="metadata"><div>Period covered: <strong>{brief.period.covered}</strong></div><div>Holdings tracked: {brief.portfolio.owned.map((ticker, index) => <span key={ticker}><strong>{ticker}</strong>{index < brief.portfolio.owned.length - 1 ? ", " : ""}</span>)} · watching: {brief.portfolio.watching.map(ticker => <span key={ticker}>{ticker} <small className="watch-inline">WATCH</small>{" "}</span>)}</div><div>Filings in window: <strong>{brief.period.filings_in_window}</strong> indexed · <strong>{brief.period.analyzed_filings}</strong> analyzed</div></div></header>
    {actionError && <div className="notice">{actionError}</div>}<JobProgress job={job} />
    <section className="section"><SectionHeader index="01" title="Critical red flags" />{brief.critical_red_flags.length ? brief.critical_red_flags.map(filing => <FilingItemCard key={filing.accession} filing={filing} />) : <p className="empty-line">None. No critical or high-severity findings in this window.</p>}</section>
    <section className="section"><SectionHeader index="02" title="What changed" />{brief.what_changed.length ? brief.what_changed.map((row, index) => <article key={`${row.ticker}-${index}`}><div className="mono muted">### {row.ticker} ({row.impact_class}) — via {row.via}</div><p className="prose">{row.net_read}</p><div className="channels">{row.channels.map(channel => <span className={`channel ${channel.direction}`} key={channel.label}>{channel.label} ({channel.direction}{channel.magnitude ? `, ${channel.magnitude}` : ""})</span>)}</div><p className="gln">Guidance: {row.guidance} · Liquidity: {row.liquidity} · Net: {row.net}</p>{row.risk_factor_changes && <p className="gln">Risk-factor changes: {row.risk_factor_changes}</p>}</article>) : <p className="empty-line">No portfolio-relevant transmission analysis in this window.</p>}</section>
    <section className="section"><SectionHeader index="03" title="Thesis impact" />{brief.thesis_impact.length ? <ul>{brief.thesis_impact.map(row => <li key={row.ticker}><strong>{row.ticker}:</strong> {row.no_thesis ? "no thesis provided — RipplX degrades gracefully without one" : `thesis ${row.verdict}`}</li>)}</ul> : <p className="empty-line">No owned position had an assessable thesis impact in this window.</p>}</section>
    <section className="section"><SectionHeader index="04" title="Verified numbers" /><p className="metric-caption">Computed by versioned deterministic formulas from SEC XBRL facts (never by the LLM) and traceable to those facts. ✓ = a computed value; — = not applicable or data missing.</p>{brief.verified_numbers.map(issuer => <article key={issuer.ticker}><h3 className="issuer-title">{issuer.ticker}</h3>{issuer.empty ? <p className="empty-line">{issuer.ticker}: {issuer.empty}</p> : <MetricTable rows={issuer.rows} />}</article>)}</section>
    <section className="section"><SectionHeader index="05" title="Open questions" />{brief.open_questions.length ? <ul>{brief.open_questions.map((question, index) => <li className="muted" key={index}>{question}</li>)}</ul> : <p className="empty-line">None.</p>}</section>
    {brief.boring_filings && <div className="faint section">{brief.boring_filings}</div>}
    <DisclaimerFooter text={brief.disclaimer} />
    {panel === "analysis" && <Drawer title="Run analysis" onClose={closePanel}>{bootstrap.analysis_configured ? <div><p className="muted">Analyze only the newest supported filing. If it is already complete or withheld for manual review, this is a no-op.</p><button className="button primary" onClick={() => { closePanel(); start("analyze"); }}>Analyze latest filing</button></div> : <div className="notice neutral"><p>Analysis needs a language-model key and model name to read filings. Everything else — verified numbers, the demo brief, and holdings — works without one.</p><div className="actions"><button className="button secondary" onClick={() => navigate("/settings")}>Configure analysis</button><button className="button" onClick={() => navigate("/brief?demo=1")}>See the demo brief</button></div></div>}</Drawer>}
  </main>;
}
