import { useCallback, useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { api, ApiError } from "../api/client";
import { DisclaimerFooter } from "../components/DisclaimerFooter";
import { AnalysisPanel } from "../components/AnalysisPanel";
import { Drawer } from "../components/Drawer";
import { FilingItemCard } from "../components/FilingItemCard";
import { JobProgress } from "../components/JobProgress";
import { MetricTable } from "../components/MetricTable";
import { SectionHeader } from "../components/SectionHeader";
import { useBootstrap } from "../context/BootstrapContext";
import { useResource } from "../hooks/useResource";
import type { Brief, FilingType, Job } from "../types";

export function BriefPage() {
  const location = useLocation(); const navigate = useNavigate(); const { bootstrap } = useBootstrap();
  const params = new URLSearchParams(location.search); const demo = params.get("demo") === "1"; const panel = params.get("panel");
  const [job, setJob] = useState<Job | null>(null); const [actionError, setActionError] = useState("");
  const load = useCallback((signal: AbortSignal) => api<Brief>(`/api/brief?demo=${demo}`, { signal }), [demo]);
  const resource = useResource(load, [demo]);
  useEffect(() => {
    if (!job || !["queued", "running"].includes(job.state)) return;
    const timer = window.setInterval(() => api<Job>(`/api/jobs/${job.id}`).then(next => { setJob(next); if (!["queued", "running"].includes(next.state)) resource.refresh(); }).catch(reason => { setActionError(reason instanceof ApiError ? reason.message : "Job status was lost after a restart."); setJob(null); }), 700);
    return () => window.clearInterval(timer);
  }, [job, resource.refresh]);
  async function start(kind: "sync" | "analyze", formType: FilingType = "latest") { setActionError(""); const payload = formType === "latest" ? {} : { form_type: formType }; try { setJob(await api<Job>(`/api/jobs/${kind === "sync" ? "sync" : "analyze"}`, { method: "POST", body: JSON.stringify(payload) })); } catch (reason) { setActionError(reason instanceof ApiError ? reason.message : "Operation could not start."); } }
  function closePanel() { params.delete("panel"); navigate({ pathname: location.pathname, search: params.toString() }, { replace: true }); }
  if (!resource.data && resource.loading) return <main className="page"><p className="loading">Loading the brief…</p></main>;
  if (!resource.data) return <main className="page"><div className="notice">{resource.error?.message ?? "The brief is unavailable."}</div></main>;
  const brief = resource.data;
  const trackedTickers = brief.tracked_tickers;
  const answerTone = brief.answer_posture === "risk_review" ? "attention" : brief.answer_posture === "monitor" || brief.answer_posture === "positive_support" ? "calm" : "";
  return <main className="page">
    {brief.sample_data && <div className="notice neutral">Sample data · generated by the bundled recorded pipeline</div>}
    {resource.error && <div className="notice">Could not refresh. Showing the last successful brief.</div>}
    <header className="brief-header"><div><p className="page-eyebrow">Your filing watch</p><h1 className="page-title">Filing brief</h1><p className="page-subtitle">A concise, evidence-backed read on what changed across the companies you follow.</p></div><div className="actions">{!demo && trackedTickers.length > 0 && <><button className="button" onClick={() => start("sync")}><span aria-hidden="true">↻</span> Sync filings</button><button className="button primary" onClick={() => navigate("?panel=analysis")}>Analyze a filing <span aria-hidden="true">→</span></button></>} {demo && <button className="button" onClick={() => navigate("/brief")}>Exit sample</button>}</div></header>
    <section className={`brief-hero ${answerTone}`}>
      <div className="hero-copy"><span className="hero-label">Executive read</span><p className="answer-hero">{brief.answer}</p><p className="hero-note">AI-selected significance · publication gated by exact-evidence checks</p></div>
      <div className="brief-stats">
        <div><span>Period</span><strong>{brief.period.covered}</strong></div>
        <div><span>Filings</span><strong>{brief.period.filings_in_window}</strong><small>in view</small></div>
        <div><span>Analyzed</span><strong>{brief.period.analyzed_filings}</strong><small>through the gate</small></div>
        <div><span>Tracking</span><strong>{trackedTickers.length}</strong><small>{trackedTickers.length === 1 ? "company" : "companies"}</small></div>
      </div>
    </section>
    {trackedTickers.length > 0 && <div className="ticker-strip"><span>Watchlist</span>{trackedTickers.map(ticker => <span className="ticker-chip" key={ticker}>{ticker}</span>)}</div>}
    {actionError && <div className="notice">{actionError}</div>}<JobProgress job={job} />
    {!trackedTickers.length && <section className="empty-invitation"><p className="section-kicker">Start here</p><h2>Add a company you already follow.</h2><p>RipplX will watch its newest SEC filings and publish only findings that clear the evidence gate.</p><Link className="button primary" to="/companies?panel=add">Add your first ticker</Link></section>}
    {brief.tracked_but_unanalyzed && <section className="guidance-note"><div><strong>{bootstrap.analysis_configured ? "Filings are ready for analysis." : "Analysis is not configured yet."}</strong><p>{bootstrap.analysis_configured ? "Run analysis to turn the latest filing into an evidence-backed brief." : "Add a model key in Settings before running filing analysis."}</p></div>{bootstrap.analysis_configured ? <button className="button" onClick={() => navigate("?panel=analysis")}>Analyze a filing</button> : <Link className="button" to="/settings">Open settings</Link>}</section>}
    {brief.withheld_filings.length > 0 && <section className="section withheld-section"><SectionHeader index="Held back" title="Withheld analyses" /><p className="metric-caption">The gate refused to publish model-authored content from these filings. This is a deliberate trust outcome.</p>{brief.withheld_filings.map(filing => <FilingItemCard key={filing.accession} filing={filing} withholdFindings />)}</section>}
    {trackedTickers.length > 0 && <section className="section"><SectionHeader index="01 · Filing changes" title="What changed" /><p className="metric-caption">The model selects significance; RipplX independently checks that every displayed quotation matches the SEC filing exactly.</p>{brief.filings.length ? brief.filings.map(filing => <FilingItemCard key={filing.accession} filing={filing} />) : <div className="empty-state"><span aria-hidden="true">—</span><div><strong>No evidence-backed changes selected</strong><p>{brief.tracked_but_unanalyzed ? "No filing has completed analysis yet." : "The analyzed filings were routine or did not produce a finding that cleared the gate."}</p></div></div>}</section>}
    {brief.verified_numbers.length > 0 && <section className="section"><SectionHeader index="02 · SEC XBRL" title="Verified numbers" /><p className="metric-caption">Versioned formulas compute these values directly from SEC XBRL facts—never from the language model.</p>{brief.verified_numbers.map(issuer => <article className="issuer-block" key={issuer.ticker}><h3 className="issuer-title">{issuer.ticker}</h3>{issuer.empty ? <p className="empty-line">{issuer.ticker}: {issuer.empty}</p> : <MetricTable rows={issuer.rows} />}</article>)}</section>}
    {trackedTickers.length > 0 && <section className="section"><SectionHeader index="03 · Follow-up" title="Open questions" />{brief.open_questions.length ? <ul className="question-list">{brief.open_questions.map((question, index) => <li className="muted" key={index}>{question}</li>)}</ul> : <div className="empty-state compact"><span aria-hidden="true">—</span><div><strong>No open questions</strong><p>Nothing in this brief needs a follow-up review.</p></div></div>}</section>}
    {brief.boring_filings && <div className="faint section">{brief.boring_filings}</div>}
    <DisclaimerFooter text={brief.disclaimer} />
    {panel === "analysis" && <Drawer title="Run filing analysis" onClose={closePanel}><AnalysisPanel configured={bootstrap.analysis_configured} onAnalyze={formType => { closePanel(); start("analyze", formType); }} onConfigure={() => navigate("/settings")} onDemo={() => navigate("/brief?demo=1")} /></Drawer>}
  </main>;
}
