import { useState, type FormEvent } from "react";
import { api, ApiError } from "../api/client";
import { useBootstrap } from "../context/BootstrapContext";
import type { Bootstrap } from "../types";

export function SettingsPage() {
  const { bootstrap, refresh } = useBootstrap(); const [identity, setIdentity] = useState(bootstrap.sec_user_agent); const [period, setPeriod] = useState(bootstrap.period); const [extract, setExtract] = useState(bootstrap.model_extract); const [reason, setReason] = useState(bootstrap.model_reason); const [key, setKey] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function save(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); try { const payload: Record<string, unknown> = { sec_user_agent: identity, period, model_extract: extract, model_reason: reason }; if (key) payload.api_key = key; await api<Bootstrap>("/api/settings", { method: "PUT", body: JSON.stringify(payload) }); setKey(""); setMessage("Settings saved. Session credentials remain only in this server process."); refresh(); } catch (reasonValue) { setError(reasonValue instanceof ApiError ? reasonValue.message : "Settings could not be saved."); } }
  async function clearKey() { await api("/api/settings", { method: "PUT", body: JSON.stringify({ api_key: "" }) }); setMessage("Session API key cleared."); refresh(); }
  return <main className="page narrow"><h1 className="page-title section">Settings</h1><form className="form-grid" onSubmit={save}><div className="field"><label htmlFor="user-agent">SEC User-Agent identity</label><input id="user-agent" className="input mono-input" type="email" required value={identity} onChange={event => setIdentity(event.target.value)} /><p className="helper">Required by EDGAR for every reader.</p></div><div className="divider-label">Analysis configuration</div><div className="field"><label htmlFor="extract-model">Extraction model (LiteLLM model string)</label><input id="extract-model" className="input mono-input" placeholder="openai/gpt-4.1-mini" value={extract} onChange={event => setExtract(event.target.value)} /></div><div className="field"><label htmlFor="reason-model">Reasoning model (optional; defaults to extraction)</label><input id="reason-model" className="input mono-input" value={reason} onChange={event => setReason(event.target.value)} /></div><div className="field"><label htmlFor="api-key">Provider API key</label><input id="api-key" className="input mono-input" type="password" autoComplete="off" placeholder={bootstrap.api_key_configured ? `Configured from ${bootstrap.api_key_source}` : "Session only — never persisted"} value={key} onChange={event => setKey(event.target.value)} /><p className="helper">Entered keys live only in server memory and must be re-entered after restart.</p>{bootstrap.api_key_configured && <button type="button" className="button ghost" onClick={clearKey}>Clear session key</button>}</div><div className="divider-label">Reading preferences</div><div className="field"><label htmlFor="period">Default period</label><select id="period" className="input" value={period} onChange={event => setPeriod(event.target.value)}>{["30d", "60d", "90d", "180d", "1y"].map(value => <option key={value}>{value}</option>)}</select></div>{error && <div className="field-error">{error}</div>}{message && <div className="notice neutral">{message}</div>}<button className="button primary">Save settings</button></form></main>;
}
